version: '3.3'

services:

  db:
    image: postgres:12.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn django_user_management.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: