# Generated by Django 2.2.6 on 2019-10-19 23:07

from django.db import migrations
import django_iban.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='iban',
            field=django_iban.fields.IBANField(default='ES00 0000 0000 0000 0000 0000', enforce_database_constraint=True, max_length=34, unique=True),
            preserve_default=False,
        ),
    ]
